# Generated by Django 3.1.1 on 2020-10-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='address',
            field=models.CharField(max_length=500),
        ),
    ]
