# Generated by Django 3.1.1 on 2020-10-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_unreg_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='unreg_students',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
